salesforce_domain: mc.s12.exacttarget.auth.marketingcloudapis.com
subdomain: "mcgtx9kkbcy470fyfdvk0vczl1dy"

okta_domain: https://accountdev.royalcanin.com
ciam_api_url: https://prd-weu1-rc-df-ciam-api-webservice-dev.cloud-effem.com

client_id: 0oa1wzon1sbWEGKz40h8
private_key: m9j4c8aHzlS_YLSCp60DPQs4XNYmluo2Chdp5Gb70Gh0D2eZTr8MhAUsRZyw0HSl
scopes: "user.custom:register"

locale: mx_MX

conn_str: "DefaultEndpointsProtocol=https;AccountName=royalcaninedata;AccountKey=eAnZOxRyleN4zoAReb4OC2Iy88/RRahA9W2vTSqj9BV/DcxaVDpHPVGaGVuzdOWBqV4L6/cjbTDd+AStGukhog==;EndpointSuffix=core.windows.net"
container_name: sfmc-daily-data

host: "rc-sfmc-migration.database.windows.net"
database: "rc-sfmc-db"
username: "rc-sfmc-migration"
password: "!royalcanine#1"

mars_petcare_consent: "d5e5a6d5-17a2-4bb9-9803-3f81f5af14a1"
rc_mkt_consent: "d836cbce-b920-4eba-a187-14cc6a2738b2"
data_research_consent: "2925c7b3-5ec4-47a9-af88-0ee44aeb4c79"
rc_tyc_consent: "12796cd0-f61d-4a90-af52-f16872a54dcc"